### PR TITLE
Fix constructor call in README

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
@jonasfj ping on this one too, although it's obviously not blocking anything

**Review by jonasfj — APPROVED** [review]
I have no problem with this... But options are optional..

And really peiole shouldn't want to set these options :)

**Comment by jonasfj** [comment]
But there is no need for encouraging people to specify options they don't need..

**Comment by djmitche** [comment]
Well, the old example was actually incorrect :)

**Comment by jonasfj** [comment]
Oh, that's right....

**Pull request merged**
